### PR TITLE
Create update mechanism

### LINKED ISSUE #71: Installation matters
Not a critical issue, but it's a tiny effort that stops the distribution of this project.

Currently, using pyCraftr is easy for geeks.  Install pyglet, clone the repository and that's all.

For other people, it's not that easy.  This requires to know how to:
- install dependencies
- use command-line
- use git to update the game

Maybe 30 % of Linux users know how to use it.  And something like 0.05 % of Mac and Windows users do.

People both need:
- that dependencies and pyCraftr download/install in a single step
- a launcher with an icon
- an easy way to update the game

What goals we could achieve:
- have Ubuntu (sorry for other distros), MacOS and Windows installers including dependencies and launcher(s)
- add the game to the Ubuntu software center (when the project will be stable and less "alpha-like") ; that will be a good ad

What do we need:
- a name.  Now that anybody calls this "pyCraftr", why not choosing this?  See #21.
- version numbers.  I suggest http://guide.python-distribute.org/specification.html#sequence-based-scheme
- an icon
- a module structure, so that the launcher can find the game installed somewhere in PYTHON_PATH
- improve setup.py and distribute packages somewhere
- MacOS and Windows scripts to update the game, probably based on git tags
- Choose what tools to use to produce packages.  Distutils contains a way to build Ubuntu and Windows packages, but this might not be enough.

### PR DESCRIPTION
**Pull request by r58Playz**
This updates the game using requests.

EDIT: The git function has been removed in commit 947bfad

Closes #71

### CODE REVIEW

**Comment by r58Playz** [comment]
Just saying, the last line(`run('rm -rf', 'pycraft_update'))`) hasn't been tested yet.

**Comment by r58Playz** [comment]
This is all py3 code.

**Comment by r58Playz** [comment]
Basically what the update function does is it clones the repository, overwrites all the files except `update.py`, then deletes the update directory which the repository was cloned in.

**Comment by Nebual** [comment]
Good idea, but I'm not sure this is an ideal approach...

1. At this stage of development, 99% of people running this are going to be using the git version anyway, in which case updating is a simple `git pull` + relaunch. Once the game is meaningful to users who wouldn't use git directly, we'd probably produce packaged Releases (including pyglet/dependencies), possibly as a self-contained .exe. Travis/Appveyer can automate this.
2. The sorts of users who can't be served by a `git pull` likely don't have git installed to be able to run `git clone`. Replacing the `git clone` with something like (untested)
```
r = urllib.request.urlopen('https://github.com/boskee/Minecraft/archive/master.zip')
with zipfile.ZipFile(BytesIO(r.read())) as z:
    z.extractall()
```
is more portable (non-Windows), is much more efficient/fast than a `git clone` doesn't involve temporary files, and avoids `run()` in favour of pure python.
3. You still need to manually relaunch the game, hot-reloading would be sweet for development (and useful for this)... you might also be able to get away with replacing `python main.py` with `python update_and_run_main.py` which checks for + updates first, prior to `import`'ing/exec'ing the rest of the game, though that would prevent you from having a nice pyglet Update button.

**Comment by r58Playz** [comment]
That's fixed...

**Comment by r58Playz** [comment]
> Replacing the `git clone` with something like (untested)
> 
> ```
> r = urllib.request.urlopen('https://github.com/boskee/Minecraft/archive/master.zip')
> with zipfile.ZipFile(BytesIO(r.read())) as z:
>     z.extractall()
> ```
That works.

**Comment by r58Playz** [comment]
So, we need to use temporary files so that while updating, the updater does not update itself(the updater overwrites the file it is in).

**Comment by r58Playz** [comment]
Oh, in the imports the `urllif.request` needs to be changed to `urllib.request`.
Also, append this after all the imports:`from io import BytesIO`

**Pull request closed without merging**
